### ISSUE TITLE
Suggestion: support for Monero (XMR) cryptocurrency

### ISSUE THREAD

**Issue by 49kazuki** [tchoulihan/bitmerchant#1]
The Monero codebase is totally unrelated to Bitcoin, creating an almost perfect anonymous and private crypto-currency, the world needs both Bitcoin and Monero, support for the cryptonote gem would be really appreciated, you could also ask for a bounty in the official forums: https://forum.monero.cc/8/funding-required. Many including me would contribute to such a bounty. 

Thanks.

**Comment by tchoulihan** [comment]
For now, I'm not going to focus on accepting altcoins.
